# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UrbanParks
                                 A QGIS plugin
 to indices and calucaltion
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-11-26
        git sha              : $Format:%H$
        copyright            : (C) 2021 by moahmed
        email                : moha@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from typing import _SpecialForm
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QLineEdit
from qgis.core import *
from qgis.utils import iface


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .urban_parks_dialog import UrbanParksDialog
import os.path


class UrbanParks:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'UrbanParks_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Urban_parks')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('UrbanParks', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/urban_parks/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Visualising the map'),
            callback=self.run,
            parent=self.iface.mainWindow())
       

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Urban_parks'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = UrbanParksDialog()
        layers = QgsProject.instance().layerTreeRoot().children()
       
        self.dlg.combo_1.clear()
        name_cum = layers[1].layer()
        name_cum.startEditing()
        for c in name_cum.getFeatures():
            self.dlg.combo_1.addItem(c.attributes()[6])
       
        def aff() :
             layer = layers[1].layer()
             self.iface.showAttributeTable(layer)
            

        self.dlg.combo_2.clear()
        name_park = layers[0].layer()
        name_park.startEditing()

        for f in name_park.getFeatures():
            self.dlg.combo_2.addItem(f.attributes()[1])

            def aff_1() :
                 player = layers[0].layer()
                 self.iface.showAttributeTable(player)
            
        def area_():
                i = self.dlg.combo_2.currentText()
                alayer = layers[0].layer()
                for j in alayer.getFeatures():
                    if(i==j.attributes()[1]):
                      v=j.attributes()[2]
                      vr=str(v)
                      self.dlg.text_1.setText(vr)
           
        def rac_():
            x = self.dlg.combo_2.currentText()
            player = layers[0].layer()
            sum=0
             
            for u in player.getFeatures():
                
                vp=u.attributes()[2]
                sum = sum + vp
            ra_c = sum/1083462
            vrp=str(ra_c)
            self.dlg.text_2.setText(vrp)


        def ajout():
             layer = layers[0].layer()
             self.iface.showAttributeTable(layer)


        self.dlg.affiche_1.clicked.connect(aff)
        self.dlg.affiche_2.clicked.connect(aff_1) 
        self.dlg.area.clicked.connect(area_)
        self.dlg.rac.clicked.connect(rac_)
        self.dlg.ajouter.clicked.connect(ajout)
       
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
